### PR TITLE
monitoring: restore ready_for_holdover status

### PR DESCRIPTION
**Pull request by vvfedorenko**
Change the sequence of initialisation to provide proper information about SA53 MAC.

### CODE REVIEW

**Review by agagniere — APPROVED** [review]

**Comment by leoleovich** [comment]
This is a fix for https://github.com/Orolia2s/oscillatord/issues/111

**Comment by agagniere** [comment]
However this will revert #90

**Comment by leoleovich** [comment]
@agagniere is there a way to update "ready for holdover" without blocking a start?

**Comment by agagniere** [comment]
Yes I will add a commit

**Pull request closed without merging**
